name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: cd client
    - run: rm -rf public .cache
    - run: npm install
    - run: npx gatsby build
    - run: cd ..
    - run: npm run build
      env:
        CI: true


#     "build": "yarn clean && tsc",
# 		"serve": "nodemon",
# 		"develop": "concurrently 'yarn clean && yarn build' 'yarn serve'",
# 		"start": "node dist/server.js",
# 		"pre": "cd client && rm -rf public .cache && yarn install && npx gatsby build && cd ..",